default_platform(:android)

platform :android do
  desc "Deploy to Firebase"
  lane :deploy do
    begin
      # Upload to Firebase
      firebase_app_distribution(
        groups: "testers",                                  # Specify tester groups
        release_notes: "Bug fixes and improvements",        # Release notes for the testers
        apk_path: "../build/app/outputs/flutter-apk/app-release.apk",  # Path to your APK file
        firebase_cli_path: "/usr/local/bin/firebase",       # Correct path to Firebase CLI
        app: "1:1027171393908:android:e39f3278018315d7ac0c21"   # Your Firebase app ID
      )
    end
  end
end
